server:
  port: 8090

# 应用配置
app:
  config:
    # 版本，方便通过接口版本升级
    api-version: v1
    # 跨域，开发阶段可以设置为 * 不限制
    cross-origin: '*'
    # 访问频次限制
    limit-count: 10
    # 白名单，不做频次拦截[微信的openid]
    white-list: ojbZUv18lbmriaTjcCWBYkOrSbHA # 瞎配的，暂时每个用户都需要频次拦截

# 线程池配置
thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        policy: CallerRunsPolicy

# ChatGPT SDK Config
chatgpt:
  sdk:
    config:
      # 官网地址 https://api.openai.com/
      # https://service-d6wuqy4n-1320869466.cd.apigw.tencentcs.com/
      api-host: https://service-d6wuqy4n-1320869466.cd.apigw.tencentcs.com/
      # 官网申请 https://platform.openai.com/account/api-keys
      api-key: sk-FpBzSH9hJwk1FQQz21Be10DeD6B44e1c905eAaD3759923A7

      # sk-FpBzSH9hJwk1FQQz21Be10DeD6B44e1c905eAaD3759923A7
      # 自主申请 http://api.xfg.im:8080/authorize?username=xfg&password=123 - 有时效性，主要为了大家学习使用
      auth-token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ3bHkiLCJleHAiOjE3MDUxMjA2MDQsImlhdCI6MTcwNTEyMDMwNCwianRpIjoiZGMxNTc4NjUtYmZhYy00Zjk4LWFmY2UtMTE3YTU0MzdhMjViIiwidXNlcm5hbWUiOiJ3bHkifQ.-UOGyC0ZkQl3AOy7ggx1OjDHC42AgsgtbJ146nHBKGo

# 微信公众号配置信息
# originalid：原始ID
# appid：个人AppID
# token：开通接口服务自定义设置
wx:
  config:
    originalid: gh_28c92be94d7d
    appid: wxd934a0cfa25171ff
    token: bcwly



# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml
